
version: 2

models:
    - name: stg_customers
      description: "Stagging customer model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_orders
      description: "Stagging orders model"
      columns:
          - name: Order_ID
            description: "The primary key for this table"
            tests:
                - not_null
